apiVersion: v1
kind: Service
metadata:
  name: java-maven-app-service
  namespace:webapp
spec:
  selector:
    app: java-maven-app
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
